spring:  datasource:    url: jdbc:mysql://localhost/store    password: 31Ack1ag00n    username: root    driver-class-name: com.mysql.cj.jdbc.Driver       
logging:
  level:
    root: warn
    '[com.promineotech]' : debug